### PR TITLE
Perf: CU-865c8kwjn : husky installation and testing

### PR DESCRIPTION
**Pull request by sofia-gastelum**
# Fixes ticket #865c8kwjn

## Problem Description
Husky was enabled for mac because of file permissions.

## Checklist 
- [x] Passes eslint linter 
- [ ] Passes backend integration tests 
- [ ] Added tests for this change 
- [ ] Added documentation for this change 
- [ ] Removed unused packages  

## Changes proposed in this pull request
Reinstall husky on mac

## Reviewers
- @aviada-andreazayas 
- @AndresOL2001

### CODE REVIEW

**Comment by aviada-fgp** [comment]
Task linked: [CU-865c8kwjn Resolve conflicts with Husky](https://app.clickup.com/t/865c8kwjn)

**Review by esmemee — APPROVED** [review]
looks good to me =)

**Review by raulynzunza — APPROVED** [review]
### It works on Windows

**Review by JoHena — COMMENTED** [review]
add npx lint-staged

**Review by jorgelabs — APPROVED** [review]
🥇

**Pull request merged**
